# Generated by Django 3.1.2 on 2020-11-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
    ]
